### ISSUE TITLE
Example-voting-app is failing

### ISSUE THREAD

**Issue by LalatenduMohanty** [docker/example-voting-app#17]
I tried to run this application on a single node machine through docker-compose, but it failed with below errors.

```
[root@fedora-1gb-blr1-01 example-voting-app]# cat /etc/fedora-release 
Fedora release 23 (Twenty Three)
[root@fedora-1gb-blr1-01 example-voting-app]# docker -v
Docker version 1.10.3, build f476348/1.10.3
[root@fedora-1gb-blr1-01 example-voting-app]# docker-compose -v
docker-compose version 1.6.2, build 4d72027
```

`````` r
# docker-compose up
Creating volume "examplevotingapp_db-data" with default driver
Starting examplevotingapp_db_1
Starting examplevotingapp_redis_1
Starting examplevotingapp_worker_1
Starting examplevotingapp_voting-app_1
Starting examplevotingapp_result-app_1
Attaching to examplevotingapp_db_1, examplevotingapp_redis_1, examplevotingapp_worker_1, examplevotingapp_voting-app_1, examplevotingapp_result-app_1
db_1         | chmod: changing permissions of ‘/var/lib/postgresql/data’: Permission denied
redis_1      |                 _._                                                  
redis_1      |            _.-``__ ''-._                                             
redis_1      |       _.-``    `.  `_.  ''-._           Redis 3.2.0 (00000000/0) 64 bit
redis_1      |   .-`` .-```.  ```\/    _.,_ ''-._                                   
redis_1      |  (    '      ,       .-`  | `,    )     Running in standalone mode
redis_1      |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis_1      |  |    `-._   `._    /     _.-'    |     PID: 1
redis_1      |   `-._    `-._  `-./  _.-'    _.-'                                   
redis_1      |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis_1      |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
redis_1      |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis_1      |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis_1      |  |    `-._`-._        _.-'_.-'    |                                  
redis_1      |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis_1      |       `-._    `-.__.-'    _.-'                                       
redis_1      |           `-._        _.-'                                           
redis_1      |               `-.__.-'                                               
redis_1      | 
redis_1      | 1:M 10 Jun 20:15:11.818 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1      | 1:M 10 Jun 20:15:11.818 # Server started, Redis version 3.2.0
redis_1      | 1:M 10 Jun 20:15:11.818 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1      | 1:M 10 Jun 20:15:11.818 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1      | 1:M 10 Jun 20:15:11.818 * The server is now ready to accept connections on port 6379
worker_1     | Connected to redis
worker_1     | Failed to connect to db - retrying
voting-app_1 | python: can't open file 'app.py': [Errno 13] Permission denied
examplevotingapp_db_1 exited with code 1
examplevotingapp_voting-app_1 exited with code 2
result-app_1 | module.js:341
result-app_1 |     throw err;
result-app_1 |     ^
result-app_1 | 
result-app_1 | Error: Cannot find module '/app/server.js'
result-app_1 |     at Function.Module._resolveFilename (module.js:339:15)
result-app_1 |     at Function.Module._load (module.js:290:25)
result-app_1 |     at Function.Module.runMain (module.js:447:10)
result-app_1 |     at startup (node.js:148:18)
result-app_1 |     at node.js:405:3
examplevotingapp_result-app_1 exited with code 1
worker_1     | Failed to connect to db - retrying
worker_1     | Failed to connect to db - retrying
worker_1     | Failed to connect to db - retrying
worker_1     | Failed to connect to db - retrying
worker_1     | Failed to connect to db - retrying
worker_1     | Failed to connect to db - retrying
worker_1     | Failed to connect to db - retrying
worker_1     | Failed to connect to db - retrying
worker_1     | Failed to connect to db - retrying
worker_1     | Failed to connect to db - retrying
worker_1     | Failed to connect to db - retrying
worker_1     | Failed to connect to db - retrying
worker_1     | Failed to connect to db - retrying
worker_1     | Failed to connect to db - retrying
^CGracefully stopping... (press Ctrl+C again to force)
Stopping examplevotingapp_worker_1 ... done
Stopping examplevotingapp_redis_1 ... done
``````

**Comment by aprilkmace** [comment]
I ran into the exact same problem.

**Comment by ManoMarks** [comment]
@LalatenduMohanty @aprilkmace 
Fedora and Redhat use a forked version of Docker which may be part of the problem. Not sure. Try running https://get.docker.com/ and see if it works.
